name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.16.x
    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.33
    - name: Test
      run: go test -coverprofile coverage.txt -covermode=atomic ./...
    - name: Code Coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.txt
        fail_ci_if_error: true
